name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install pnpm first so that actions/setup-node caching (which calls pnpm) succeeds
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      # Corepack is not strictly necessary after pnpm/action-setup, but keep enable for local parity
      - name: Enable corepack (optional)
        run: corepack enable
      - name: Install deps
        run: pnpm install
      - name: Type check
        run: npx tsc --noEmit
      - name: Build extension
        run: pnpm build